### PR TITLE
Not Perfect

### PR DESCRIPTION
**Pull request by nazi-pira**
Here is what I have done so far but I already know there is a lot to be done.

### CODE REVIEW

**Review by HIPPIEKICK — CHANGES_REQUESTED** [review]
Hi Nazanin!
There are some changes that need to be done before approval. If you check out the inspector, you can see how your site looks on mobile (see picture). Some starting tips are to get rid of some of the fixed widths you have (we want to avoid horizontal scrolling) and decrease the font size of your title.

You also need to format the indentation of your HTML file, be consistent with whether you use semicolons or not in your JavaScript file (and remove console.logs), and think about how you're naming your classes (descriptive and kebab-case).

Check out the [general feedback document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475) as well as the [code guidelines](https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e).

Good luck and reach out if anything is unclear!
Skärmavbild 2021-02-16 kl  14 06 20

**Comment by nazi-pira** [comment]
Hi Matilda!
Thank you so much for the feedback. I will make changes and pull it again. 

Regards,
Nazanin

**Comment by HIPPIEKICK** [comment]
Hi Nazanin! There's still some horizontal scroll in mobile view that you should get rid of. Good job with the other changes!

**Comment by HIPPIEKICK** [comment]
The content is still a little bit too wide for mobile, see image. PS. Your netlify link doesn't seem to be correct.

Skärmavbild 2021-04-21 kl  10 36 14

**Comment by nazi-pira** [comment]
Fixed it!

**Review by HIPPIEKICK — APPROVED** [review]

**Pull request closed without merging**
