### PR TITLE
Technigo project week 3: Build a Business Site

### PR DESCRIPTION
**Pull request by idasylven**
This is my front end boot camp assignment number 2 creating a site for an existing or fictional company. Minimum requirements: the site should contain a responsive hero image, a functioning accordion and a fill out form.

### CODE REVIEW

**Comment by HIPPIEKICK** [comment]
Hi Ida! Can you submit a link to your netlify?

**Comment by idasylven** [comment]
Hi Matilda,

Yes, of course you can! I´m so sorry to had to contact me for the link this
week too (as you had to do that for my first project as well), my bad.

Here the Netlify link: https://fervent-wozniak-ce39dc.netlify.app/

I have also added the link to my project in README section, followed by a
push, as per you suggestion in to my question regardning this last week.

Have a nice evening!

Kind regards

**Comment by HIPPIEKICK** [comment]
> https://fervent-wozniak-ce39dc.netlify.app/

No worries, thanks 👍

**Review by HIPPIEKICK — CHANGES_REQUESTED** [review]
Hi Ida! Please have a look at my comments about indentation, removing unused code, the `for`-`id` connection. Check out the [general feedback document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475) for further reference and tips. Also have a look at the responsiveness of your page since some of your content is too wide to fit.

**Comment by idasylven** [comment]
THANK YOU for all the great comments for me to be able to improve my project - they have been very helpful!

I have (and hopefully in a successful manner) now revised:

- Various elements in the HTML structure for a more semantic approach
- Removed unused code, fixed some crazy indentation and updated the inconsistent use of semicolon
- Adjusted responsiveness for mobile, tablet and desktop
- Edited the README section

I also have some questions:

- I can´t seem to target the span-class "first-letter" in CSS (declared on line 50 in the HTML). I would like to make the initial "A" of the company title slightly bigger in tablet and desktop view. I have googled on how to target a span class (some suggested using pseudo-classes etc) but I can´t really get it to work...
- I´m a bit curious if you are able to declare multiple font sizes as a root (primary, secondary etc) in the beginning of the CSS file? I realised I have re-used font size 12, 14 and 16 a lot throughout my styling and was wondering if there is cleaner and a less repetitive way of doing this? 

Many thanks for now!

**Comment by HIPPIEKICK** [comment]
> THANK YOU for all the great comments for me to be able to improve my project - they have been very helpful!
> 
> I have (and hopefully in a successful manner) now revised:
> 
> * Various elements in the HTML structure for a more semantic approach
> * Removed unused code, fixed some crazy indentation and updated the inconsistent use of semicolon
> * Adjusted responsiveness for mobile, tablet and desktop
> * Edited the README section
> 
> I also have some questions:
> 
> * I can´t seem to target the span-class "first-letter" in CSS (declared on line 50 in the HTML). I would like to make the initial "A" of the company title slightly bigger in tablet and desktop view. I have googled on how to target a span class (some suggested using pseudo-classes etc) but I can´t really get it to work...
> * I´m a bit curious if you are able to declare multiple font sizes as a root (primary, secondary etc) in the beginning of the CSS file? I realised I have re-used font size 12, 14 and 16 a lot throughout my styling and was wondering if there is cleaner and a less repetitive way of doing this?
> 
> Many thanks for now!

Hi Ida!
You need to check the comments about the for-id connection again. Read more about it [here](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475#d8458e7f4cf540999b578b3de4fc1088) if you want.

Regarding your questions, it seems like the first letter is targeted correctly! It's nice that you're thinking of ways to not repeat yourself. Look into _CSS custom properties_ and try it out to see if you feel like you get better power of your properties. I found this [article](https://www.smashingmagazine.com/2018/05/css-custom-properties-strategy-guide/) that might be of value.

**Comment by idasylven** [comment]
Hi Matilda,

Thank you for reviewing this project once again! Hopefully I have now revised the required for-id attributes pair correctly. Please let me know if otherwise 😀

**Review by HIPPIEKICK — APPROVED** [review]

**Pull request closed without merging**
